spring.output.ansi.enabled: always

io.rsocket.routing.broker:
  broker-id: 11111111-1111-1111-1111-111111111111
  tcp.port: 8001
  cluster.tcp.port: 7001

logging:
  level:
    io.rsocket.routing.broker: DEBUG
#---
#spring.config.activate.on-profile: broker2
#
#io.rsocket.routing.broker:
#  broker-id: 22222222-2222-2222-2222-222222222222
#  tcp.port: 8002
#  cluster.tcp:
#    port: 7002
#  brokers:
#  - cluster.tcp:
#      host: localhost
#      port: 7001
#    proxy.tcp:
#      host: localhost
#      port: 8001
